import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// List of all NJ municipalities with their counties
const NJ_MUNICIPALITIES = [
  // Atlantic County
  { name: "Absecon", county: "Atlantic" },
  { name: "Atlantic City", county: "Atlantic" },
  { name: "Brigantine", county: "Atlantic" },
  { name: "Buena", county: "Atlantic" },
  { name: "Buena Vista Township", county: "Atlantic" },
  { name: "Corbin City", county: "Atlantic" },
  { name: "Egg Harbor City", county: "Atlantic" },
  { name: "Egg Harbor Township", county: "Atlantic" },
  { name: "Estell Manor", county: "Atlantic" },
  { name: "Folsom", county: "Atlantic" },
  { name: "Galloway Township", county: "Atlantic" },
  { name: "Hamilton Township", county: "Atlantic" },
  { name: "Hammonton", county: "Atlantic" },
  { name: "Linwood", county: "Atlantic" },
  { name: "Longport", county: "Atlantic" },
  { name: "Margate City", county: "Atlantic" },
  { name: "Mullica Township", county: "Atlantic" },
  { name: "Northfield", county: "Atlantic" },
  { name: "Pleasantville", county: "Atlantic" },
  { name: "Port Republic", county: "Atlantic" },
  { name: "Somers Point", county: "Atlantic" },
  { name: "Ventnor City", county: "Atlantic" },
  { name: "Weymouth Township", county: "Atlantic" },

  // Bergen County (partial list - there are 70 municipalities)
  { name: "Allendale", county: "Bergen" },
  { name: "Alpine", county: "Bergen" },
  { name: "Bergenfield", county: "Bergen" },
  { name: "Bogota", county: "Bergen" },
  { name: "Carlstadt", county: "Bergen" },
  { name: "Cliffside Park", county: "Bergen" },
  { name: "Closter", county: "Bergen" },
  { name: "Cresskill", county: "Bergen" },
  { name: "Demarest", county: "Bergen" },
  { name: "Dumont", county: "Bergen" },
  { name: "East Rutherford", county: "Bergen" },
  { name: "Edgewater", county: "Bergen" },
  { name: "Elmwood Park", county: "Bergen" },
  { name: "Emerson", county: "Bergen" },
  { name: "Englewood", county: "Bergen" },
  { name: "Englewood Cliffs", county: "Bergen" },
  { name: "Fair Lawn", county: "Bergen" },
  { name: "Fairview", county: "Bergen" },
  { name: "Fort Lee", county: "Bergen" },
  { name: "Franklin Lakes", county: "Bergen" },
  { name: "Garfield", county: "Bergen" },
  { name: "Glen Rock", county: "Bergen" },
  { name: "Hackensack", county: "Bergen" },
  { name: "Harrington Park", county: "Bergen" },
  { name: "Hasbrouck Heights", county: "Bergen" },
  { name: "Haworth", county: "Bergen" },
  { name: "Hillsdale", county: "Bergen" },
  { name: "Ho-Ho-Kus", county: "Bergen" },
  { name: "Leonia", county: "Bergen" },
  { name: "Little Ferry", county: "Bergen" },
  { name: "Lodi", county: "Bergen" },
  { name: "Lyndhurst", county: "Bergen" },
  { name: "Mahwah", county: "Bergen" },
  { name: "Maywood", county: "Bergen" },
  { name: "Midland Park", county: "Bergen" },
  { name: "Montvale", county: "Bergen" },
  { name: "Moonachie", county: "Bergen" },
  { name: "New Milford", county: "Bergen" },
  { name: "North Arlington", county: "Bergen" },
  { name: "Northvale", county: "Bergen" },
  { name: "Norwood", county: "Bergen" },
  { name: "Oakland", county: "Bergen" },
  { name: "Old Tappan", county: "Bergen" },
  { name: "Oradell", county: "Bergen" },
  { name: "Palisades Park", county: "Bergen" },
  { name: "Paramus", county: "Bergen" },
  { name: "Park Ridge", county: "Bergen" },
  { name: "Ramsey", county: "Bergen" },
  { name: "Ridgefield", county: "Bergen" },
  { name: "Ridgefield Park", county: "Bergen" },
  { name: "Ridgewood", county: "Bergen" },
  { name: "River Edge", county: "Bergen" },
  { name: "River Vale", county: "Bergen" },
  { name: "Rochelle Park", county: "Bergen" },
  { name: "Rockleigh", county: "Bergen" },
  { name: "Rutherford", county: "Bergen" },
  { name: "Saddle Brook", county: "Bergen" },
  { name: "Saddle River", county: "Bergen" },
  { name: "South Hackensack", county: "Bergen" },
  { name: "Teaneck", county: "Bergen" },
  { name: "Tenafly", county: "Bergen" },
  { name: "Teterboro", county: "Bergen" },
  { name: "Upper Saddle River", county: "Bergen" },
  { name: "Waldwick", county: "Bergen" },
  { name: "Wallington", county: "Bergen" },
  { name: "Washington Township", county: "Bergen" },
  { name: "Westwood", county: "Bergen" },
  { name: "Woodcliff Lake", county: "Bergen" },
  { name: "Wood-Ridge", county: "Bergen" },
  { name: "Wyckoff", county: "Bergen" },

  // Burlington County (partial list)
  { name: "Bass River Township", county: "Burlington" },
  { name: "Beverly", county: "Burlington" },
  { name: "Bordentown", county: "Burlington" },
  { name: "Bordentown Township", county: "Burlington" },
  { name: "Burlington", county: "Burlington" },
  { name: "Burlington Township", county: "Burlington" },
  { name: "Chesterfield Township", county: "Burlington" },
  { name: "Cinnaminson Township", county: "Burlington" },
  { name: "Delanco Township", county: "Burlington" },
  { name: "Delran Township", county: "Burlington" },
  { name: "Eastampton Township", county: "Burlington" },
  { name: "Edgewater Park Township", county: "Burlington" },
  { name: "Evesham Township", county: "Burlington" },
  { name: "Fieldsboro", county: "Burlington" },
  { name: "Florence Township", county: "Burlington" },
  { name: "Hainesport Township", county: "Burlington" },
  { name: "Lumberton Township", county: "Burlington" },
  { name: "Mansfield Township", county: "Burlington" },
  { name: "Maple Shade Township", county: "Burlington" },
  { name: "Medford", county: "Burlington" },
  { name: "Medford Lakes", county: "Burlington" },
  { name: "Moorestown Township", county: "Burlington" },
  { name: "Mount Holly Township", county: "Burlington" },
  { name: "Mount Laurel Township", county: "Burlington" },
  { name: "New Hanover Township", county: "Burlington" },
  { name: "North Hanover Township", county: "Burlington" },
  { name: "Palmyra", county: "Burlington" },
  { name: "Pemberton", county: "Burlington" },
  { name: "Pemberton Township", county: "Burlington" },
  { name: "Riverside Township", county: "Burlington" },
  { name: "Riverton", county: "Burlington" },
  { name: "Shamong Township", county: "Burlington" },
  { name: "Southampton Township", county: "Burlington" },
  { name: "Springfield Township", county: "Burlington" },
  { name: "Tabernacle Township", county: "Burlington" },
  { name: "Washington Township", county: "Burlington" },
  { name: "Westampton Township", county: "Burlington" },
  { name: "Willingboro Township", county: "Burlington" },
  { name: "Woodland Township", county: "Burlington" },
  { name: "Wrightstown", county: "Burlington" },

  // Camden County (partial list)
  { name: "Audubon", county: "Camden" },
  { name: "Audubon Park", county: "Camden" },
  { name: "Barrington", county: "Camden" },
  { name: "Bellmawr", county: "Camden" },
  { name: "Berlin", county: "Camden" },
  { name: "Berlin Township", county: "Camden" },
  { name: "Brooklawn", county: "Camden" },
  { name: "Camden", county: "Camden" },
  { name: "Cherry Hill Township", county: "Camden" },
  { name: "Chesilhurst", county: "Camden" },
  { name: "Clementon", county: "Camden" },
  { name: "Collingswood", county: "Camden" },
  { name: "Gibbsboro", county: "Camden" },
  { name: "Gloucester City", county: "Camden" },
  { name: "Gloucester Township", county: "Camden" },
  { name: "Haddon Heights", county: "Camden" },
  { name: "Haddon Township", county: "Camden" },
  { name: "Haddonfield", county: "Camden" },
  { name: "Hi-Nella", county: "Camden" },
  { name: "Laurel Springs", county: "Camden" },
  { name: "Lawnside", county: "Camden" },
  { name: "Lindenwold", county: "Camden" },
  { name: "Magnolia", county: "Camden" },
  { name: "Merchantville", county: "Camden" },
  { name: "Mount Ephraim", county: "Camden" },
  { name: "Oaklyn", county: "Camden" },
  { name: "Pennsauken Township", county: "Camden" },
  { name: "Pine Hill", county: "Camden" },
  { name: "Pine Valley", county: "Camden" },
  { name: "Runnemede", county: "Camden" },
  { name: "Somerdale", county: "Camden" },
  { name: "Stratford", county: "Camden" },
  { name: "Tavistock", county: "Camden" },
  { name: "Voorhees Township", county: "Camden" },
  { name: "Waterford Township", county: "Camden" },
  { name: "Winslow Township", county: "Camden" },
  { name: "Woodlynne", county: "Camden" },

  // Essex County (partial list)
  { name: "Belleville", county: "Essex" },
  { name: "Bloomfield", county: "Essex" },
  { name: "Caldwell", county: "Essex" },
  { name: "Cedar Grove", county: "Essex" },
  { name: "East Orange", county: "Essex" },
  { name: "Essex Fells", county: "Essex" },
  { name: "Fairfield", county: "Essex" },
  { name: "Glen Ridge", county: "Essex" },
  { name: "Irvington", county: "Essex" },
  { name: "Livingston", county: "Essex" },
  { name: "Maplewood", county: "Essex" },
  { name: "Millburn", county: "Essex" },
  { name: "Montclair", county: "Essex" },
  { name: "Newark", county: "Essex" },
  { name: "North Caldwell", county: "Essex" },
  { name: "Nutley", county: "Essex" },
  { name: "Orange", county: "Essex" },
  { name: "Roseland", county: "Essex" },
  { name: "South Orange Village", county: "Essex" },
  { name: "Verona", county: "Essex" },
  { name: "West Caldwell", county: "Essex" },
  { name: "West Orange", county: "Essex" },

  // Hudson County
  { name: "Bayonne", county: "Hudson" },
  { name: "East Newark", county: "Hudson" },
  { name: "Guttenberg", county: "Hudson" },
  { name: "Harrison", county: "Hudson" },
  { name: "Hoboken", county: "Hudson" },
  { name: "Jersey City", county: "Hudson" },
  { name: "Kearny", county: "Hudson" },
  { name: "North Bergen", county: "Hudson" },
  { name: "Secaucus", county: "Hudson" },
  { name: "Union City", county: "Hudson" },
  { name: "Weehawken", county: "Hudson" },
  { name: "West New York", county: "Hudson" },

  // Middlesex County (partial list)
  { name: "Carteret", county: "Middlesex" },
  { name: "Cranbury", county: "Middlesex" },
  { name: "Dunellen", county: "Middlesex" },
  { name: "East Brunswick", county: "Middlesex" },
  { name: "Edison", county: "Middlesex" },
  { name: "Helmetta", county: "Middlesex" },
  { name: "Highland Park", county: "Middlesex" },
  { name: "Jamesburg", county: "Middlesex" },
  { name: "Metuchen", county: "Middlesex" },
  { name: "Middlesex", county: "Middlesex" },
  { name: "Milltown", county: "Middlesex" },
  { name: "Monroe Township", county: "Middlesex" },
  { name: "New Brunswick", county: "Middlesex" },
  { name: "North Brunswick Township", county: "Middlesex" },
  { name: "Old Bridge Township", county: "Middlesex" },
  { name: "Perth Amboy", county: "Middlesex" },
  { name: "Piscataway Township", county: "Middlesex" },
  { name: "Plainsboro Township", county: "Middlesex" },
  { name: "Sayreville", county: "Middlesex" },
  { name: "South Amboy", county: "Middlesex" },
  { name: "South Brunswick Township", county: "Middlesex" },
  { name: "South Plainfield", county: "Middlesex" },
  { name: "South River", county: "Middlesex" },
  { name: "Spotswood", county: "Middlesex" },
  { name: "Woodbridge Township", county: "Middlesex" },

  // Monmouth County (partial list)
  { name: "Aberdeen Township", county: "Monmouth" },
  { name: "Allenhurst", county: "Monmouth" },
  { name: "Allentown", county: "Monmouth" },
  { name: "Asbury Park", county: "Monmouth" },
  { name: "Atlantic Highlands", county: "Monmouth" },
  { name: "Avon-by-the-Sea", county: "Monmouth" },
  { name: "Belmar", county: "Monmouth" },
  { name: "Bradley Beach", county: "Monmouth" },
  { name: "Brielle", county: "Monmouth" },
  { name: "Colts Neck Township", county: "Monmouth" },
  { name: "Deal", county: "Monmouth" },
  { name: "Eatontown", county: "Monmouth" },
  { name: "Englishtown", county: "Monmouth" },
  { name: "Fair Haven", county: "Monmouth" },
  { name: "Farmingdale", county: "Monmouth" },
  { name: "Freehold", county: "Monmouth" },
  { name: "Freehold Township", county: "Monmouth" },
  { name: "Hazlet Township", county: "Monmouth" },
  { name: "Highlands", county: "Monmouth" },
  { name: "Holmdel Township", county: "Monmouth" },
  { name: "Howell Township", county: "Monmouth" },
  { name: "Interlaken", county: "Monmouth" },
  { name: "Keansburg", county: "Monmouth" },
  { name: "Keyport", county: "Monmouth" },
  { name: "Lake Como", county: "Monmouth" },
  { name: "Little Silver", county: "Monmouth" },
  { name: "Loch Arbour", county: "Monmouth" },
  { name: "Long Branch", county: "Monmouth" },
  { name: "Manalapan Township", county: "Monmouth" },
  { name: "Manasquan", county: "Monmouth" },
  { name: "Marlboro Township", county: "Monmouth" },
  { name: "Matawan", county: "Monmouth" },
  { name: "Middletown Township", county: "Monmouth" },
  { name: "Millstone Township", county: "Monmouth" },
  { name: "Monmouth Beach", county: "Monmouth" },
  { name: "Neptune Township", county: "Monmouth" },
  { name: "Neptune City", county: "Monmouth" },
  { name: "Ocean Township", county: "Monmouth" },
  { name: "Oceanport", county: "Monmouth" },
  { name: "Red Bank", county: "Monmouth" },
  { name: "Roosevelt", county: "Monmouth" },
  { name: "Rumson", county: "Monmouth" },
  { name: "Sea Bright", county: "Monmouth" },
  { name: "Sea Girt", county: "Monmouth" },
  { name: "Shrewsbury", county: "Monmouth" },
  { name: "Shrewsbury Township", county: "Monmouth" },
  { name: "Spring Lake", county: "Monmouth" },
  { name: "Spring Lake Heights", county: "Monmouth" },
  { name: "Tinton Falls", county: "Monmouth" },
  { name: "Union Beach", county: "Monmouth" },
  { name: "Upper Freehold Township", county: "Monmouth" },
  { name: "Wall Township", county: "Monmouth" },
  { name: "West Long Branch", county: "Monmouth" },

  // Morris County (partial list)
  { name: "Boonton", county: "Morris" },
  { name: "Boonton Township", county: "Morris" },
  { name: "Butler", county: "Morris" },
  { name: "Chatham", county: "Morris" },
  { name: "Chatham Township", county: "Morris" },
  { name: "Chester", county: "Morris" },
  { name: "Chester Township", county: "Morris" },
  { name: "Denville Township", county: "Morris" },
  { name: "Dover", county: "Morris" },
  { name: "East Hanover Township", county: "Morris" },
  { name: "Florham Park", county: "Morris" },
  { name: "Hanover Township", county: "Morris" },
  { name: "Harding Township", county: "Morris" },
  { name: "Jefferson Township", county: "Morris" },
  { name: "Kinnelon", county: "Morris" },
  { name: "Lincoln Park", county: "Morris" },
  { name: "Long Hill Township", county: "Morris" },
  { name: "Madison", county: "Morris" },
  { name: "Mendham", county: "Morris" },
  { name: "Mendham Township", county: "Morris" },
  { name: "Mine Hill Township", county: "Morris" },
  { name: "Montville Township", county: "Morris" },
  { name: "Morris Plains", county: "Morris" },
  { name: "Morris Township", county: "Morris" },
  { name: "Morristown", county: "Morris" },
  { name: "Mount Arlington", county: "Morris" },
  { name: "Mount Olive Township", county: "Morris" },
  { name: "Mountain Lakes", county: "Morris" },
  { name: "Netcong", county: "Morris" },
  { name: "Parsippany-Troy Hills Township", county: "Morris" },
  { name: "Pequannock Township", county: "Morris" },
  { name: "Randolph Township", county: "Morris" },
  { name: "Riverdale", county: "Morris" },
  { name: "Rockaway", county: "Morris" },
  { name: "Rockaway Township", county: "Morris" },
  { name: "Roxbury Township", county: "Morris" },
  { name: "Victory Gardens", county: "Morris" },
  { name: "Washington Township", county: "Morris" },
  { name: "Wharton", county: "Morris" },

  // Passaic County
  { name: "Bloomingdale", county: "Passaic" },
  { name: "Clifton", county: "Passaic" },
  { name: "Haledon", county: "Passaic" },
  { name: "Hawthorne", county: "Passaic" },
  { name: "Little Falls", county: "Passaic" },
  { name: "North Haledon", county: "Passaic" },
  { name: "Passaic", county: "Passaic" },
  { name: "Paterson", county: "Passaic" },
  { name: "Pompton Lakes", county: "Passaic" },
  { name: "Prospect Park", county: "Passaic" },
  { name: "Ringwood", county: "Passaic" },
  { name: "Totowa", county: "Passaic" },
  { name: "Wanaque", county: "Passaic" },
  { name: "Wayne", county: "Passaic" },
  { name: "West Milford", county: "Passaic" },
  { name: "Woodland Park", county: "Passaic" },

  // Union County
  { name: "Berkeley Heights", county: "Union" },
  { name: "Clark", county: "Union" },
  { name: "Cranford", county: "Union" },
  { name: "Elizabeth", county: "Union" },
  { name: "Fanwood", county: "Union" },
  { name: "Garwood", county: "Union" },
  { name: "Hillside", county: "Union" },
  { name: "Kenilworth", county: "Union" },
  { name: "Linden", county: "Union" },
  { name: "Mountainside", county: "Union" },
  { name: "New Providence", county: "Union" },
  { name: "Plainfield", county: "Union" },
  { name: "Rahway", county: "Union" },
  { name: "Roselle", county: "Union" },
  { name: "Roselle Park", county: "Union" },
  { name: "Scotch Plains", county: "Union" },
  { name: "Springfield", county: "Union" },
  { name: "Summit", county: "Union" },
  { name: "Union", county: "Union" },
  { name: "Westfield", county: "Union" },
  { name: "Winfield", county: "Union" },
];

async function main() {
  console.log('🌱 Starting seed...');
  
  // Insert or update municipalities
  let count = 0;
  for (const muni of NJ_MUNICIPALITIES) {
    await prisma.municipality.upsert({
      where: { name: muni.name },
      update: {
        county: muni.county,
        state: 'NJ',
      },
      create: {
        name: muni.name,
        county: muni.county,
        state: 'NJ',
      },
    });
    count++;
    if (count % 50 === 0) {
      console.log(`✅ Upserted ${count} municipalities...`);
    }
  }
  
  console.log(`✅ Seeded ${count} municipalities`);
  
  // Get counts by county
  const countyStats = await prisma.municipality.groupBy({
    by: ['county'],
    _count: true,
  });
  
  console.log('\n📊 Municipalities by county:');
  countyStats.forEach(stat => {
    console.log(`  ${stat.county}: ${stat._count}`);
  });
  
  console.log('\n🌱 Seed completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });